// <auto-generated />
using LikeFinal_Version.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LikeFinal_Version.Migrations
{
    [DbContext(typeof(ContextData))]
    [Migration("20210710004046_SeventhMigration")]
    partial class SeventhMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LikeFinal_Version.Models.Facebook", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoinsNumber");

                    b.Property<string>("ImgUrl");

                    b.Property<int>("IsClicked");

                    b.Property<string>("ItemLink");

                    b.Property<string>("ItemTybe");

                    b.Property<int>("UserNumber");

                    b.Property<int>("VideoTime");

                    b.HasKey("ItemID");

                    b.ToTable("Facebook");
                });

            modelBuilder.Entity("LikeFinal_Version.Models.FacebookOperations", b =>
                {
                    b.Property<int>("OperationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemID");

                    b.Property<int>("UserID");

                    b.HasKey("OperationID");

                    b.ToTable("FacebookOperations");
                });

            modelBuilder.Entity("LikeFinal_Version.Models.Instegram", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoinsNumber");

                    b.Property<string>("ImgUrl");

                    b.Property<int>("IsClicked");

                    b.Property<string>("ItemLink");

                    b.Property<string>("ItemTybe");

                    b.Property<int>("UserNumber");

                    b.Property<int>("VideoTime");

                    b.HasKey("ItemID");

                    b.ToTable("Instegram");
                });

            modelBuilder.Entity("LikeFinal_Version.Models.InstegramOperations", b =>
                {
                    b.Property<int>("OperationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemID");

                    b.Property<int>("UserID");

                    b.HasKey("OperationID");

                    b.ToTable("InstegramOperations");
                });

            modelBuilder.Entity("LikeFinal_Version.Models.Operation", b =>
                {
                    b.Property<int>("OperationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemID");

                    b.Property<int>("UserID");

                    b.HasKey("OperationID");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("LikeFinal_Version.Models.ShareLinkOperations", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NewPartner");

                    b.Property<int>("OldPartner");

                    b.HasKey("ID");

                    b.ToTable("ShareLinkOperations");
                });

            modelBuilder.Entity("LikeFinal_Version.Models.TikTok", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoinsNumber");

                    b.Property<string>("ImgUrl");

                    b.Property<int>("IsClicked");

                    b.Property<string>("ItemLink");

                    b.Property<string>("ItemTybe");

                    b.Property<int>("UserNumber");

                    b.Property<int>("VideoTime");

                    b.HasKey("ItemID");

                    b.ToTable("TikTok");
                });

            modelBuilder.Entity("LikeFinal_Version.Models.TikTokOperations", b =>
                {
                    b.Property<int>("OperationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemID");

                    b.Property<int>("UserID");

                    b.HasKey("OperationID");

                    b.ToTable("TikTokOperations");
                });

            modelBuilder.Entity("LikeFinal_Version.Models.Twitter", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoinsNumber");

                    b.Property<string>("ImgUrl");

                    b.Property<int>("IsClicked");

                    b.Property<string>("ItemLink");

                    b.Property<string>("ItemTybe");

                    b.Property<int>("UserNumber");

                    b.Property<int>("VideoTime");

                    b.HasKey("ItemID");

                    b.ToTable("Twitter");
                });

            modelBuilder.Entity("LikeFinal_Version.Models.TwitterOperations", b =>
                {
                    b.Property<int>("OperationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemID");

                    b.Property<int>("UserID");

                    b.HasKey("OperationID");

                    b.ToTable("TwitterOperations");
                });

            modelBuilder.Entity("LikeFinal_Version.Models.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BirthDay");

                    b.Property<int>("Coins");

                    b.Property<int>("DayOfYear");

                    b.Property<int>("NumberOfLuck");

                    b.Property<string>("UserEmail");

                    b.Property<string>("UserName");

                    b.Property<string>("UserPassword");

                    b.Property<string>("UserPhoto");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LikeFinal_Version.Models.Youtubes", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoinsNumber");

                    b.Property<string>("ImgUrl");

                    b.Property<int>("IsClicked");

                    b.Property<string>("ItemLink");

                    b.Property<string>("ItemTybe");

                    b.Property<int>("UserNumber");

                    b.Property<int>("VideoTime");

                    b.HasKey("ItemID");

                    b.ToTable("Youtubes");
                });
#pragma warning restore 612, 618
        }
    }
}
